Repository aplijobs/birdwoot, pull requests merged in 2023-04, with the labels that each got.

#33 RELEASE 23.14.01
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  .github/workflows/lock.yml
  .github/workflows/nightly_installer.yml
  .github/workflows/publish_codespace_image.yml
  .github/workflows/publish_foss_docker.yml
  .github/workflows/stale.yml
  Gemfile
  Gemfile.lock
  config/environments/staging.rb
  docker/Dockerfile
  docker/dockerfiles/sidekiq.Dockerfile
  scripts/build_slack_deployment_status_notification_payload.sh
Labels: cm-changes

#36 Fix | Footer background color
  app/javascript/widget/components/ChatInputWrap.vue
Labels: 1 min review

#29 bump sentry vue sentry tracing and sentry vue
  package.json
  yarn.lock
Labels: 1 min review

#37 Feature || add sentry release version with put parameter
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
Labels: 1 min review

#39 Feature || apm config
  .env.example
  app/javascript/apm/index.js
Labels: 1 min review

#40 Feature | Add sentry config and implementation
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/packs/application.js
  app/javascript/packs/widget.js
  app/javascript/shared/utils/exceptions.js
  app/javascript/widget/store/modules/conversation/actions.js
Labels: 10 min review

#43 Feature || cause error on purpose to test sentry in staging
  app/javascript/widget/store/modules/conversation/actions.js
Labels: 1 min review

#45 Add type to AWS SSM put-parameter action
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#48 Feature | Add harcoded env vars just for testing
  docker-compose.yaml
  docker/dockerfiles/webpack.Dockerfile
Labels: 1 min review

#49 Adding --overwrite to aws ssm put-parameter for SSM_VUE_APP_VERSION
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#46 Enhancement | Error feedback for failed messages
  .husky/pre-commit
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/UserMessage.vue
Labels: 1 min review

#53 Feature || remove prev env vars config
  app/javascript/widget/store/modules/conversation/actions.js
  docker-compose.yaml
  docker/dockerfiles/webpack.Dockerfile
Labels: 1 min review

#55 removing duplicated VUE_APP_SENTRY_DSN_CHAT
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#58 add shell
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#59 Fix whitespaces issue in action.yml
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#60 Removing VUE_APP_SENTRY_DSN_CHAT and passing VUE_APP_VERSION as docker env
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  docker/dockerfiles/webpack.Dockerfile
Labels: 1 min review

#63 Feature || Add cache for docker build and push from github actions
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#66 Feature || revertCacheChanges
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#64 Feature || Create env file and add env vars directly in github actions
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_staging.yml
Labels: 1 min review

#67 Feature | try to add env files modifying dockerfile
  .dockerignore
  .github/actions/deployment/push-image-ecr/action.yml
  docker/Dockerfile
Labels: 1 min review
