Repository aplijobs/birdwoot, pull requests merged in 2023-03, with the labels that each got.

#11 Feature || Add correct svg document on FileBubble
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/widget/components/FileBubble.vue
Labels: 5 min review

#15 Feature | New send button
  app/javascript/widget/components/ChatFooter.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/ChatSendButton.vue
Labels: feature, Priority: Low, 5 min review

#17 Enhancement | Mobile UX
  README.md
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/ConversationWrap.vue
  app/views/widgets/show.html.erb
Labels: 1 min review

#23 Sync with Chatwoot
  app/controllers/api/v1/accounts/inboxes_controller.rb
  app/controllers/api/v1/accounts/microsoft/authorizations_controller.rb
  app/controllers/api/v2/accounts/reports_controller.rb
  app/controllers/microsoft/callbacks_controller.rb
  app/helpers/api/v2/accounts/reports_helper.rb
  app/javascript/dashboard/api/reports.js
  app/javascript/dashboard/modules/search/components/SearchHeader.vue
  app/javascript/dashboard/modules/search/components/SearchTabs.vue
  app/javascript/dashboard/modules/search/components/SearchView.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/AddLabel.vue
  app/javascript/dashboard/routes/dashboard/settings/labels/EditLabel.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/LiveReports.vue
  app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/MetricCard.vue
  app/javascript/dashboard/store/modules/reports.js
  app/models/contact_inbox.rb
  app/views/api/v2/accounts/reports/conversation_traffic.erb
  config/locales/en.yml
  config/routes.rb
  spec/controllers/api/v1/accounts/contacts/contact_inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/inboxes_controller_spec.rb
  spec/controllers/api/v1/accounts/microsoft/authorization_controller_spec.rb
  spec/controllers/api/v2/accounts/report_controller_spec.rb
  yarn.lock
Labels: 1 min review

#25 add checkout to deploy staging
  .github/workflows/deploy_staging.yml
Labels: 5 min review

#26 Feature | Add Slack notification to Staging deployment
  .github/workflows/deploy_staging.yml
  scripts/build_slack_deployment_status_notification_payload.sh
Labels: 5 min review

#27 Fix | Add executable permission to Slack script
  scripts/build_slack_deployment_status_notification_payload.sh
Labels: 1 min review

#28 Enhancement | Clean up Github workflows
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/lock.yml
  .github/workflows/nightly_installer.yml
  .github/workflows/publish_codespace_image.yml
  .github/workflows/publish_foss_docker.yml
  .github/workflows/stale.yml
Labels: enhancement, Priority: Low, 1 min review

#30 Enhancement | Update Dockerfile to cache gems and yarn packages
  docker/Dockerfile
Labels: 1 min review

#31 Fix | Add `localhost` gem to `Gemfile.lock`
  Gemfile.lock
Labels: 1 min review
