Repository aplijobs/birdwoot, pull requests merged in 2023-05, with the labels that each got.

#68 Fix/ revert to SSM Put parameters config
  .dockerignore
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  config/webpacker.yml
  docker/Dockerfile
  docker/dockerfiles/webpack.Dockerfile
  package.json
  yarn.lock
Labels: 1 min review

#69 Maintenance | Update Slack script output
  scripts/build_slack_deployment_status_notification_payload.sh
Labels: enhancement, Priority: Low, 1 min review

#70 Fix | add s to inputs
  .github/actions/deployment/push-image-ecr/action.yml
Labels: 1 min review

#78 Using sidekiq_alive for healthcheck
  Gemfile
  Gemfile.lock
  app/controllers/sidekiq_health_check_controller.rb
  config/routes.rb
  docker/Dockerfile
  docker/entrypoints/rails.sh
  sidekiq_docker_wrapper.sh
Labels: 1 min review

#79 Fix | Format Quick Replies message
  app/javascript/shared/components/ChatOptions.vue
  app/javascript/widget/components/AgentMessageBubble.vue
Labels: 1 min review

#80 Enhancement | Improve scrolling UX for quick replies
  app/javascript/widget/components/QuickReplies.vue
Labels: 1 min review

#77 Updating custom attributes when referral param is passed
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/views/Home.vue
Labels: 1 min review

#84 Release 23.20.01
  .env.example
  .github/actions/deployment/push-image-ecr/action.yml
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
  .husky/pre-commit
  .ruby-version
  Gemfile
  Gemfile.lock
  app/javascript/apm/index.js
  app/javascript/dashboard/store/modules/conversations/actions.js
  app/javascript/packs/application.js
  app/javascript/packs/sdk.js
  app/javascript/packs/widget.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/components/ChatOptions.vue
  app/javascript/shared/components/FluentIcon/icons.json
  app/javascript/shared/utils/exceptions.js
  app/javascript/widget/assets/scss/views/_conversation.scss
  app/javascript/widget/components/AgentMessageBubble.vue
  app/javascript/widget/components/ChatInputWrap.vue
  app/javascript/widget/components/QuickReplies.vue
  app/javascript/widget/components/UserMessage.vue
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/views/Home.vue
  docker/dockerfiles/webpack.Dockerfile
  package.json
  scripts/build_slack_deployment_status_notification_payload.sh
  yarn.lock
Labels: 10 min review

#85 Enhancement | Support multi-line text in Interactive Messages
  app/javascript/shared/components/ChatOptions.vue
Labels: 1 min review

#86 Fix ref references with referral full name
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/views/Home.vue
Labels: 1 min review

#87 Release 23.20.02
  app/javascript/packs/sdk.js
  app/javascript/sdk/IFrameHelper.js
  app/javascript/shared/components/ChatOptions.vue
  app/javascript/widget/store/modules/conversation/actions.js
  app/javascript/widget/views/Home.vue
Labels: 1 min review

#89 Security | Adding CORS domain restriction based on webwidget url and widget filtering
  app/controllers/widgets_controller.rb
  config/initializers/cors.rb
Labels: 5 min review

#90 Adding CORS_WIDGET_CONFIG on deployment env vars
  .github/workflows/deploy_production.yml
  .github/workflows/deploy_staging.yml
Labels: 1 min review
